### ISSUE TITLE
use of jarbundler fails: unsupporte major.minor version 51.0

### ISSUE THREAD

**Issue by RBornat** [tofi86/Jarbundler#3]
I cloned your jarbundler (got 2.5.0). Did ant jar (I'm using java 1.7), put jarbundler-2.5.0 in my ant library, tried to use it with this bit of xml:

```
<taskdef name="jarbundler" 
     classname="net.sourceforge.jarbundler.JarBundler" />
```

...
        <jarbundler dir="build"
                    name="Jape"
                    mainclass="uk.org.jape.Jape"
                    jar="../java_GUI/build/jar/OSX/Jape.jar"
                    shortname="Jape"
                    icon="Jape.icns"
                    stubfile="universalJavaApplicationStub"
                    useJavaXKey="true"
                    version="7"
                    >

```
        <javaproperty name="apple.laf.useScreenMenuBar" value="true"/>
        <javaproperty name="apple.awt.showGrowBox"      value="true"/>
        <javaproperty name="apple.awt.antialiasing"     value="true"/>
        <javaproperty name="apple.awt.rendering"        value="quality"/>
        <javaproperty name="uk.org.jape.AppPackage"     value="$APP_PACKAGE"/>
        <documenttype name="Jape Theory"
                            extensions= "jt,j,jp" 
                            ostypes=    "****" 
                            iconfile=   "Jape.icns"
                            role=       "None"/>
    </jarbundler>
```

and I got the error message 

/Users/richard/gitrepositories/japery/jape/distrib/MacOSX/build.xml:10: java.lang.UnsupportedClassVersionError: net/sourceforge/jarbundler/JarBundler : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)

I know that java 1.7 is 51.0. Is there something wrong with the way I build JarBundler? (You don't seem to distribute a binary version.)

**Comment by RBornat** [comment]
Whoops, The task I use is

```
    <jarbundler dir="build"
                name="Jape"
                mainclass="uk.org.jape.Jape"
                jar="../java_GUI/build/jar/OSX/Jape.jar"
                shortname="Jape"
                icon="Jape.icns"
                stubfile="universalJavaApplicationStub"
                useJavaXKey="true"
                version="7"
                >

        <javaproperty name="apple.laf.useScreenMenuBar" value="true"/>
        <javaproperty name="apple.awt.showGrowBox"      value="true"/>
        <javaproperty name="apple.awt.antialiasing"     value="true"/>
        <javaproperty name="apple.awt.rendering"        value="quality"/>
        <javaproperty name="uk.org.jape.AppPackage"     value="$APP_PACKAGE"/>
        <documenttype name="Jape Theory"
                            extensions= "jt,j,jp" 
                            ostypes=    "****" 
                            iconfile=   "Jape.icns"
                            role=       "None"/>
    </jarbundler>
```

**Comment by RBornat** [comment]
Whoops. Found my problem. Not your fault. Sorry sorry sorry.
